name: conda-pkgdown

on: [push, pull_request]

jobs:
  build-conda-deploy-pkgdown:
    name: Build conda package & deploy pkgdown website
    if: "! startsWith(github.event.head_commit.message, 'bump ') || startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          # Do everything inside the base env
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          mamba-version: "*"
          channels: "pdiakumis,conda-forge,bioconda"

      - name: Conda package build and upload
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          mamba install conda-build conda-verify anaconda-client
          mamba build --R 4.0 deploy/conda-recipe/
          PKG_PATH="/usr/share/miniconda/conda-bld/linux-64/r-gpgr-*.tar.bz2"
          anaconda -t ${{ secrets.ANACONDA_UPLOAD_TOKEN }} upload $PKG_PATH

      - name: Install conda packages
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: mamba create -n pkgdown_gpgr --use-local r-gpgr r-pkgdown pandoc

      - name: Publish pkgdown website
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            conda activate pkgdown_gpgr
            printf "gpgr version:\n"
            Rscript -e "packageVersion('gpgr')"
            printf "pkgdown version:\n"
            Rscript -e "packageVersion('pkgdown')"
            Rscript -e 'pkgdown::deploy_to_branch(branch = "gh-pages", new_process = FALSE)'

